InternManager/Controllers/TeacherController.cs
using InternManager.Business.Abstract;
using InternManager.Business.Concrate;
using InternManager.Entities.Concrate;
using InternManager.WebUI.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Data.OleDb;
using System.Data.SqlClient;
using System.Data;
using System.Drawing;
using System.IO;
using System.Security.Cryptography;
using System.Security.Policy;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using System.Collections.Generic;
using ExcelDataReader;
using Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure;
using System.Linq;
using Microsoft.AspNetCore.DataProtection;

namespace InternManager.WebUI.Controllers
{
    public class TeacherController : Controller
    {

        private IPersonManager _personManager;
        private ITeacherManager _teacherManager;
        private IInternManager _internManager;
        private IIntern1Manager _intern1Manager;
        private IIntern2Manager _intern2Manager;
        private IISEManager _iseManager;
        private IStudentManager _studentManager;
        private IHostingEnvironment Environment;
        private IConfiguration Configuration;
        public static string myId;
        public static string myPath;
        public static string myStudentsId;
        public static Person _person;
        public string[] _studentPass = new string[1];
        public static Teacher teacher;
        public static Teacher myTeacher;
        public static List<Person> mPersons;
        public static Student myStudents = new Student();
        public TeacherController(IISEManager iseManager,IIntern2Manager intern2Manager,  IIntern1Manager intern1Manager, IInternManager internManager, IHostingEnvironment _environment, IConfiguration _configuration, IStudentManager studentManager, IPersonManager personManager, ITeacherManager teacherManager)
        {
            _iseManager = iseManager;
            _intern2Manager = intern2Manager;
            _intern1Manager = intern1Manager;
            _internManager = internManager;
            Environment = _environment;
            Configuration = _configuration;
            _studentManager = studentManager;
            _personManager = personManager;
            _teacherManager = teacherManager;
        }


        [HttpGet]
        public IActionResult Index(Teacher teacher)
        {

            var person = _personManager.Get(teacher.PersonId.ToString());
            myTeacher = teacher;
            if (person.Image != null)
            {
                string myPath = BossModel.ByteArrayToImageAsync(person.Image);
                ViewData["path"] = myPath;
            }

            ViewData["Name"] = person.NameSurname;
            ViewData["Id"] = teacher.TeacherNumber;
            myId = teacher.TeacherNumber;

            ViewData["gDate"] = DateTime.Now.ToString("d");

            var intern1Det = _internManager.GetById("Staj1");
            var intern2Det = _internManager.GetById("Staj2");
            var iseDET = _internManager.GetById("ISE");

            if (intern1Det != null)
            {
                ViewData["Staj1Type"] = intern1Det.Type;
                ViewData["Staj1Tarih"] = intern1Det.RecStart.ToString("d");
                ViewData["Staj1Tarih2"] = intern1Det.RecEnd.ToString("d");
                ViewData["Staj1TarihV1"] = intern1Det.RecFileStart2.ToString("d");
                ViewData["Staj1TarihV2"] = intern1Det.RecFileStart2.ToString("d");
            }
            if (intern2Det != null)
            {
                ViewData["Staj2Type"] = intern2Det.Type;
                ViewData["Staj2Tarih"] = intern2Det.RecStart.ToString("d");
                ViewData["Staj2Tarih2"] = intern2Det.RecEnd.ToString("d");
                ViewData["Staj2Tarih2V1"] = intern2Det.RecFileStart2.ToString("d");
                ViewData["Staj2Tarih2V2"] = intern2Det.RecFileStart2.ToString("d");
            }
            if (iseDET != null)
            {
                ViewData["IseType"] = iseDET.Type;
                ViewData["ISE"] = iseDET.RecStart.ToString("d");
                ViewData["ISE2"] = iseDET.RecEnd.ToString("d");
                ViewData["ISE2V1"] = iseDET.RecFileStart2.ToString("d");
                ViewData["ISE2V2"] = iseDET.RecFileStart2.ToString("d");
            }

            myTeacher = _teacherManager.GetById(teacher.TeacherNumber.ToString());
            return View(teacher);
        }


        [HttpPost]
        public async Task<IActionResult> Index(string number, string password, IFormFile file = null)
        {
            var model = _teacherManager.GetById(number);
            var persons = _personManager.Get(model.PersonId.ToString());
            MD5 md5 = new MD5CryptoServiceProvider();
            md5.ComputeHash(ASCIIEncoding.ASCII.GetBytes(password));
            byte[] result = md5.Hash;
            StringBuilder strBuilder = new StringBuilder();
            for (int i = 0; i < result.Length; i++)
            {
                strBuilder.Append(result[i].ToString("x2"));
            }

            model.TeacherPassword = strBuilder.ToString();
            model.IsFirstPassword = true;
            if (file != null)
            {
                var path = Path.Combine(
                            Directory.GetCurrentDirectory(), "wwwroot\\img",
                            file.FileName);
                using (var stream = new FileStream(path, FileMode.Create))
                {
                    await file.CopyToAsync(stream);
                }
                var image = new Bitmap(path);
                persons.Image = BossModel.ImageToByteArray(image);
            }
            _personManager.Update(persons);
            _teacherManager.Update(model);

            return RedirectToAction("TeacherLogin", "Home");
        }

        [HttpGet]
        public IActionResult ListStaj1()
        {
            TeacherModel model = new TeacherModel();
            var internList = _intern1Manager.GetAll();
            model.Teacher = teacher;
            List<Student> tempList = new List<Student>();
            if (internList != null)
            {
                foreach (var item in internList)
                {
                    if (item.TeacherId == myTeacher.Id)
                    {
                        tempList.Add(_studentManager.Get(item.Student_Id.ToString()));
                    }
                }
            }
            model.StudentList = tempList;
            ViewData["path"] = myPath;
            ViewData["Name"] = _person.NameSurname;
            return View(model);
        }

        [HttpGet]
        public IActionResult Staj1Detail(string id)
        {
            myStudentsId = id;
            TeacherModel model = new TeacherModel();
            var internList = _intern1Manager.GetById(id);
            myStudents = _studentManager.GetById(id);
            if (internList.DetailDocument2!=null)
            {
                ViewBag.staj1Yüklendi = true;
                if (internList.IsOk==true)
                {
                    ViewBag.Onaylandi = true;
                }
                else
                {
                    ViewBag.Onaylandi = false;
                }
            }
            ViewData["path"] = myPath;
            ViewData["Name"] = _person.NameSurname;
            return View();

        }

        [HttpGet]
        public IActionResult Staj2Detail(string id)
        {
            myStudentsId = id;
            TeacherModel model = new TeacherModel();
            var internList = _intern2Manager.GetById(id);
            myStudents = _studentManager.GetById(id);
            if (internList.DetailDocument2 != null)
            {
                ViewBag.staj1Yüklendi = true;
                if (internList.IsOk == true)
                {
                    ViewBag.Onaylandi = true;
                }
                else
                {
                    ViewBag.Onaylandi = false;
                }
            }
            ViewData["path"] = myPath;
            ViewData["Name"] = _person.NameSurname;
            return View();

        }
        [HttpGet]
        public IActionResult IMEDetails(string id)
        {
            myStudentsId = id;
            TeacherModel model = new TeacherModel();
            var internList = _iseManager.GetById(id);
            myStudents = _studentManager.GetById(id);
            if (internList.DetailDocument2 != null)
            {
                ViewBag.staj1Yüklendi = true;
                if (internList.IsOk == true)
                {
                    ViewBag.Onaylandi = true;
                }
                else
                {
                    ViewBag.Onaylandi = false;
                }
            }
            ViewData["path"] = myPath;
            ViewData["Name"] = _person.NameSurname;
            return View();

        }

        [HttpPost]
        public IActionResult downloadDefterStaj1(string myFileseas)
        {
            var mIntern = _intern1Manager.GetById(myStudents.Id.ToString());
            var getStudent = _studentManager.Get(myStudents.Id.ToString());
            if (mIntern.DetailDocument != null)
            {
                byte[] byteArr = mIntern.DetailDocument;
                string namePipe = "application/pdf";
                return new FileContentResult(byteArr, namePipe)
                {
                    FileDownloadName = $"{myStudents.StudentNumber}_StajDefteri(Staj1).pdf"
                };
            }
            return RedirectToAction("Intern1Main", "Boss", myStudentsId);
        }
        [HttpPost]
        public IActionResult downloadDefterStaj2(string myFileseas)
        {
            var mIntern = _intern2Manager.GetById(myStudents.Id.ToString());
            var getStudent = _studentManager.Get(myStudents.Id.ToString());
            if (mIntern.DetailDocument != null)
            {

InternManager/Views/Teacher/IMEDetails.cshtml
@model StudentModel
@{
    Layout = "_Layout";
}

@section info{
    <div class="user_img">
        <img class="img-responsive"
         src="@ViewData["Path"]"
         alt="#" />
    </div>
    <div class="user_info">
        <h6>@ViewData["Name"]</h6>
        <p><span class="online_animation"></span>Komisyon</p>
    </div>
}
    @section menus{
    <li>
        <a href="#apps" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="fa fa-object-group blue2_color"></i> <span>Staj İşlemleri</span></a>
        <ul class="collapse list-unstyled" id="apps">
            <li><a asp-action="ListStaj1" asp-controller="Teacher"><span>Staj-1</span></a></li>
            <li><a asp-action="ListStaj2" asp-controller="Teacher"><span>Staj-2</span></a></li>
            <li><a asp-action="ListIME" asp-controller="Teacher"><span>ISE</span></a></li>
        </ul>
    </li>

    }
    @section pages{
    <div class="row column1 d-flex" style="display:flex;">
        <div class="col-md-3" style="margin-left:2%">
            <div class="full counter_section margin_bottom_30">
                <div class="couter_icon">
                    <div>
                        <i class="fa fa-clock-o blue1_color"></i>
                    </div>
                </div>
                <div class="p-5 counter_no">
                    <div>

                        @if (ViewBag.staj1Yüklendi)
                        {
                            if (ViewBag.Onaylandi)
                            {
                                <h3 class="mt-5 text-center bg-success text-dark">Staj-1 Onaylanmis</h3>
                                @using (Html.BeginForm("downloadDefterIME", "Teacher", FormMethod.Post))
                                {
                                    <input type="submit" id="btnCancel" value="Indir" />
                                }
                            }
                            else
                            {
                                @using (Html.BeginForm("downloadDefterIME", "Teacher", FormMethod.Post))
                                {
                                    <input type="submit" id="btnCancel" value="Indir" />
                                }
                                @using (Html.BeginForm("durumDegisIME", "Teacher", FormMethod.Post))
                                {
                                    <label>Onayla</label>
                                    <input type="radio" asp-for="Intern1s.IsOk2" value="1" />
                                    <label>Onaylama</label>
                                    <input type="radio" asp-for="Intern1s.IsOk2" value="0" />
                                    <label>Onaylandıysanız veya onaylamadıysanız nedeni </label>
                                    <input type="text" asp-for="Intern1s.Info"  />
                                    <label>Kabul Edilen Günler</label>
                                    <input type="text" asp-for="Intern1s.OkDays"  />
                                    <input type="submit" id="btnCancel" value="Indir" />
                                }
                            }
                        }
                        else
                        {
                            <h3 class="mt-5 text-center bg-danger text-dark">Staj-1 Başvuru Formu Yüklenmemiş</h3>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
    }

InternManager/Views/Teacher/Index.cshtml
@model Teacher
@{
    Layout = "_Layout";
}
@if (Model.IsFirstPassword == true)
{
    @section mainLink{
    <a
        <img class="logo_icon img-responsive"
         src="https://seeklogo.com/images/K/kocaeli___niversitesi-logo-440B62032E-seeklogo.com.png"
         alt="#" />
            </a>
    }
    @section info{
    <div class="user_img">
        <img class="img-responsive"
         src="@ViewData["Path"]"
         alt="#" />
    </div>
    <div class="user_info">
        <h6>
            @ViewData["Name"]
        </h6>
        <p><span class="online_animation"></span>Öğrenci</p>
    </div>
}
    @section pages{

    <div class="row column1 d-flex" style="display:flex;">
        <div class="col-md-3" style="margin-left:2%">
            <div class="full counter_section margin_bottom_30">
                <div class="couter_icon">
                    <div>
                        <i class="fa fa-clock-o blue1_color"></i>
                    </div>
                </div>
                <div class="counter_no">
                    <div>
                        <a asp-action="Intern1Main" asp-controller="Student" class="counter_no">
                            <div>
                                <p class="head_couter">STAJ-1</p>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3" style="margin-left:5%">
            <div class="full counter_section margin_bottom_30">
                <div class="couter_icon">
                    <div>
                        <i class="fa fa-clock-o blue1_color"></i>
                    </div>
                </div>
                <div class="counter_no">
                    <div>
                        <a asp-action="Intern2Main" asp-controller="Student" class="counter_no">
                            <div>
                                <p class="head_couter">STAJ-2</p>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class=" col-md-3" style="margin-left:5%">
            <div class="full counter_section margin_bottom_30">
                <div class="couter_icon">
                    <div>
                        <i class="fa fa-clock-o blue1_color"></i>
                    </div>
                </div>
                <div class="counter_no">
                    <div>
                        <a asp-action="ISEMAIN" asp-controller="Student" class="counter_no">
                            <div>
                                <p class="head_couter">IME</p>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row column4 graph">
        <div class="col-md-11 margin_bottom_30">
            <div class="dash_blog">
                <div class="dash_blog_inner">
                    <div class="dash_head">
                        <h3><span><i class="fa fa-calendar"></i>&nbsp @ViewData["gDate"]</span></h3>
                    </div>
                    <div class="list_cont">
                        <p>Staj Yönetimi</p>
                    </div>
                    <div class="task_list_main">
                        <ul class="task_list">
                            <li>
                                <a>STAJ1</a><br><strong>
                                    @ViewData["Staj1Tarih"] /  @ViewData["Staj1Tarih2"]
                                    Or
                                    @ViewData["Staj1TarihV1"] /  @ViewData["Staj1TarihV2"]
                                </strong>
                            </li>
                            <li>
                                <a>STAJ2</a><br><strong>
                                    @ViewData["Staj2Tarih"] /  @ViewData["Staj2Tarih2"]
                                    Or
                                    @ViewData["Staj2Tarih2V1"] /  @ViewData["Staj2Tarih2V2"]
                                </strong>
                            </li>
                            <li>
                                <a>İşyerinde Mesleki Eğitim</a><br><strong>
                                    @ViewData["ISE"] /  @ViewData["ISE2"]
                                    Or
                                    @ViewData["ISE2V1"] /  @ViewData["ISE2V2"]
                                </strong>
                            </li>

                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="container-fluid">
            <div class="footer">
                <p>
                    Kocaeli Universitesi Öğrencileri Tarafindan Yapilmistir<br><br>
                    Distributed By:Caner Ay Celep , Eyup Ayaz , İsa Oguz , Mehmet Yusuf Alpay<a href="https://themewagon.com/">®</a>
                </p>
            </div>
        </div>
    </div>
    }
    @section menus{
    <li>
        <a href="#apps" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="fa fa-object-group blue2_color"></i> <span>Staj İşlemleri</span></a>
        <ul class="collapse list-unstyled" id="apps">
            <li><a asp-action="ListStaj1" asp-controller="Teacher"><span>Staj-1</span></a></li>
            <li><a asp-action="ListStaj2" asp-controller="Teacher"><span>Staj-2</span></a></li>
            <li><a asp-action="ListIME" asp-controller="Teacher"><span>ISE</span></a></li>
        </ul>
    </li>

    }
}

@if (Model.IsFirstPassword == false)
{
    @section pages{

    <div class="card">
        <div class="login">

            <div class="login-header">

                <div class="img-content"> <img class="logos" src="https://seeklogo.com/images/K/kocaeli___niversitesi-logo-440B62032E-seeklogo.com.png"></div>
                <h3>Lütfen ilk giriş için şifrenizi değiştiriniz ve bir fotoğraf yükleyiniz !.</h3>

                <form asp-controller="Student" asp-action="Index" method="post" enctype="multipart/form-data">
                    <div class="form-group">
                        <label for="number">Ogrenci Numarasi</label>
                        <input hidden name="number" id="number" type="text" placeholder="@Model.TeacherNumber" value="@Model.TeacherNumber" />
                    </div>
                    <div class="form-group">
                        <label for="password">Şifreniz : </label>
                        <input required type="password" name="password" id="password" class="btn btn-primary" />
                    </div>
                        @if (ViewData["path"] == null)
                        {
                            <div class="form-group">
                                <label>Resim Seçin</label>
                                <input required type="file" name="file" id="file" />
                            </div>
                        }
                        else
                        {
                            <div class="form-group">
                                <label hidden>Resim Seçin</label>
                                <input hidden type="file" name="file" id="file" />
                            </div>
                        }

                        <button type="submit" class="btn btn-primary">Save Blog</button>
                    </form>

                </div>
            </div>

        </div>
        }
}

InternManager/Views/Teacher/ListIME.cshtml
@model TeacherModel

@section info{
    <div class="user_img">
        <img class="img-responsive"
         src="@ViewData["Path"]"
         alt="#" />
    </div>
    <div class="user_info">
        <h6>@ViewData["Name"]</h6>
        <p><span class="online_animation"></span>Komisyon</p>
    </div>
}
    @section pages{
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Öğrenci Numarasi</th>
                <th scope="col">Ogrenci TelNo</th>
            </tr>
        </thead>
        <tbody class="table-group-divider">
            @foreach (var item in Model.StudentList)
            {
                <tr>
                    <th scope="row">1</th>
                    <td>@item.StudentNumber</td>
                    <td>@item.StudentMail</td>
                    <td><a asp-action="IMEDetails" asp-controller="Teacher" asp-route-id="@item.StudentNumber">Detay</a></td>
                </tr>
            }
        </tbody>
    </table>
}

InternManager/Views/Teacher/ListStaj1.cshtml
@model TeacherModel

@section info{
    <div class="user_img">
        <img class="img-responsive"
         src="@ViewData["Path"]"
         alt="#" />
    </div>
    <div class="user_info">
        <h6>@ViewData["Name"]</h6>
        <p><span class="online_animation"></span>Komisyon</p>
    </div>
}
@section pages{
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Öğrenci Numarasi</th>
                <th scope="col">Ogrenci TelNo</th>
            </tr>
        </thead>
        <tbody class="table-group-divider">
            @foreach (var item in Model.StudentList)
            {
                <tr>
                    <th scope="row">1</th>
                    <td>@item.StudentNumber</td>
                    <td>@item.StudentMail</td>
                    <td><a asp-action="Staj1Details" asp-controller="Teacher" asp-route-id="@item.StudentNumber">Detay</a></td>
                </tr>
            }
        </tbody>
    </table>
}

InternManager/Views/Teacher/ListStaj2.cshtml
@model TeacherModel

@section info{
    <div class="user_img">
        <img class="img-responsive"
         src="@ViewData["Path"]"
         alt="#" />
    </div>
    <div class="user_info">
        <h6>@ViewData["Name"]</h6>
        <p><span class="online_animation"></span>Komisyon</p>
    </div>
}
    @section pages{
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Öğrenci Numarasi</th>
                <th scope="col">Ogrenci TelNo</th>
            </tr>
        </thead>
        <tbody class="table-group-divider">
            @foreach (var item in Model.StudentList)
            {
                <tr>
                    <th scope="row">1</th>
                    <td>@item.StudentNumber</td>
                    <td>@item.StudentMail</td>
                    <td><a asp-action="Staj2Details" asp-controller="Teacher" asp-route-id="@item.StudentNumber">Detay</a></td>
                </tr>
            }
        </tbody>
    </table>
}

InternManager/Views/Teacher/Staj1Detail.cshtml
@model StudentModel
@{
    Layout = "_Layout";
}

@section info{
    <div class="user_img">
        <img class="img-responsive"
         src="@ViewData["Path"]"
         alt="#" />
    </div>
    <div class="user_info">
        <h6>@ViewData["Name"]</h6>
        <p><span class="online_animation"></span>Komisyon</p>
    </div>
}
    @section menus{
    <li>
        <a href="#apps" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="fa fa-object-group blue2_color"></i> <span>Staj İşlemleri</span></a>
        <ul class="collapse list-unstyled" id="apps">
            <li><a asp-action="ListStaj1" asp-controller="Teacher"><span>Staj-1</span></a></li>
            <li><a asp-action="ListStaj2" asp-controller="Teacher"><span>Staj-2</span></a></li>
            <li><a asp-action="ListIME" asp-controller="Teacher"><span>ISE</span></a></li>
        </ul>
    </li>

    }
    @section pages{
    <div class="row column1 d-flex" style="display:flex;">
        <div class="col-md-3" style="margin-left:2%">
            <div class="full counter_section margin_bottom_30">
                <div class="couter_icon">
                    <div>
                        <i class="fa fa-clock-o blue1_color"></i>
                    </div>
                </div>
                <div class="p-5 counter_no">
                    <div>

                        @if (ViewBag.staj1Yüklendi)
                        {
                            if (ViewBag.Onaylandi)
                            {
                                <h3 class="mt-5 text-center bg-success text-dark">Staj-1 Onaylanmis</h3>
                                @using (Html.BeginForm("downloadDefterStaj1", "Teacher", FormMethod.Post))
                                {
                                    <input type="submit" id="btnCancel" value="Indir" />
                                }
                            }
                            else
                            {
                                @using (Html.BeginForm("downloadDefterStaj1", "Teacher", FormMethod.Post))
                                {
                                    <input type="submit" id="btnCancel" value="Indir" />
                                }
                                @using (Html.BeginForm("durumDegis", "Teacher", FormMethod.Post))
                                {
                                    <label>Onayla</label>
                                    <input type="radio" asp-for="Intern1s.IsOk2" value="1" />
                                    <label>Onaylama</label>
                                    <input type="radio" asp-for="Intern1s.IsOk2" value="0" />
                                    <label>Onaylandıysanız veya onaylamadıysanız nedeni </label>
                                    <input type="text" asp-for="Intern1s.Info"  />
                                    <label>Kabul Edilen Günler</label>
                                    <input type="text" asp-for="Intern1s.OkDays" />
                                    <input type="submit" id="btnCancel" value="Indir" />
                                }
                            }
                        }
                        else
                        {
                            <h3 class="mt-5 text-center bg-danger text-dark">Staj-1 Başvuru Formu Yüklenmemiş</h3>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
    }

InternManager/Views/Teacher/Staj2Detail.cshtml
@model StudentModel
@{
    Layout = "_Layout";
}

@section info{
    <div class="user_img">
        <img class="img-responsive"
         src="@ViewData["Path"]"
         alt="#" />
    </div>
    <div class="user_info">
        <h6>@ViewData["Name"]</h6>
        <p><span class="online_animation"></span>Komisyon</p>
    </div>
}
    @section menus{
    <li>
        <a href="#apps" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="fa fa-object-group blue2_color"></i> <span>Staj İşlemleri</span></a>
        <ul class="collapse list-unstyled" id="apps">
            <li><a asp-action="ListStaj1" asp-controller="Teacher"><span>Staj-1</span></a></li>
            <li><a asp-action="ListStaj2" asp-controller="Teacher"><span>Staj-2</span></a></li>
            <li><a asp-action="ListIME" asp-controller="Teacher"><span>ISE</span></a></li>
        </ul>
    </li>

    }
    @section pages{
    <div class="row column1 d-flex" style="display:flex;">
        <div class="col-md-3" style="margin-left:2%">
            <div class="full counter_section margin_bottom_30">
                <div class="couter_icon">
                    <div>
                        <i class="fa fa-clock-o blue1_color"></i>
                    </div>
                </div>
                <div class="p-5 counter_no">
                    <div>

                        @if (ViewBag.staj1Yüklendi)
                        {
                            if (ViewBag.Onaylandi)
                            {
                                <h3 class="mt-5 text-center bg-success text-dark">Staj-1 Onaylanmis</h3>
                                @using (Html.BeginForm("downloadDefterStaj2", "Teacher", FormMethod.Post))
                                {
                                    <input type="submit" id="btnCancel" value="Indir" />
                                }
                            }
                            else
                            {
                                @using (Html.BeginForm("downloadDefterStaj2", "Teacher", FormMethod.Post))
                                {
                                    <input type="submit" id="btnCancel" value="Indir" />
                                }
                                @using (Html.BeginForm("durumDegisStaj2", "Teacher", FormMethod.Post))
                                {
                                    <label>Onayla</label>
                                    <input type="radio" asp-for="Intern1s.IsOk2" value="1" />
                                    <label>Onaylama</label>
                                    <input type="radio" asp-for="Intern1s.IsOk2" value="0" />
                                    <label>Onaylandıysanız veya onaylamadıysanız nedeni </label>
                                    <input type="text" asp-for="Intern1s.Info"  />
                                    <label>Kabul Edilen Günler</label>
                                    <input type="text" asp-for="Intern1s.OkDays"  />
                                    <input type="submit" id="btnCancel" value="Indir" />
                                }
                            }
                        }
                        else
                        {
                            <h3 class="mt-5 text-center bg-danger text-dark">Staj-2 Defteri Yüklenmemiş</h3>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
    }